// Generated by GraphWalker (http://www.graphwalker.org)
package org.isf.testautomation;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.isf.utils.exception.OHException;
import org.isf.utils.exception.OHServiceException;
import org.graphwalker.java.annotation.Edge;

@Model(file = "org/myorg/testautomation/VaccineBrowserManager.json")
public interface OH {

    @Vertex()
    void v_NotEmptyList();

    @Vertex()
    void v_EmptyList();
    
    @Vertex()
    void v_OHException();

    @Edge()
    void e_addVaccine();

    @Edge()
    void e_removeVaccine();
    
    @Edge()
    void e_updateVaccine();
    
    @Edge()
    void e_addEmpty();

    @Edge()
    void e_removeEmpty();
    
    @Edge()
    void e_addUsedCode();
    
    @Edge()
    void e_addLongCode();
    
    @Edge()
    void e_addEmptyCode();
    
    @Edge()
    void e_addEmptyDescription();
    
    @Edge()
    void e_return();
   
}
