/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 20 13:18:58 GMT 2024
 */

package org.isf.vaccine.test;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.isf.vaccine.manager.VaccineBrowserManager;
import org.isf.vaccine.model.Vaccine;
import org.isf.vactype.model.VaccineType;
import org.junit.runner.RunWith;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VaccineBrowserManager_ESTest extends VaccineBrowserManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      VaccineType vaccineType0 = new VaccineType();
      Vaccine vaccine0 = new Vaccine("{nPK+}O,,,w}67rXS=~", "{nPK+}O,,,w}67rXS=~", vaccineType0);
      vaccine0.setCode("");
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.newVaccine(vaccine0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }

//  @Test(timeout = 4000)
//  public void test01()  throws Throwable  {
//      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
//      VaccineType vaccineType0 = new VaccineType();
//      Vaccine vaccine0 = new Vaccine("S", "S", vaccineType0);
//      vaccineBrowserManager0.validateVaccine(vaccine0, false);
//      assertEquals("S", vaccine0.getDescription());
//  }
//
//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
//      VaccineType vaccineType0 = new VaccineType("File {} loaded.", "File {} loaded.");
//      Vaccine vaccine0 = new Vaccine("File {} loaded.", "File {} loaded.", vaccineType0);
//      try { 
//        vaccineBrowserManager0.validateVaccine(vaccine0, false);
//        fail("Expecting exception: Exception");
//      
//      } catch(Exception e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
//      }
//  }

//  @Test(timeout = 4000)
//  public void test03()  throws Throwable  {
//      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
//      Vaccine vaccine0 = new Vaccine();
//      // Undeclared exception!
//      try { 
//        vaccineBrowserManager0.validateVaccine(vaccine0, true);
//        fail("Expecting exception: NullPointerException");
//      
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.getVaccine("1,o'");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.isCodePresent("dicomPatientBirthDate");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      VaccineType vaccineType0 = new VaccineType();
      Vaccine vaccine0 = new Vaccine("dicomStudyDescription =", "dicomStudyDescription =", vaccineType0);
      try { 
        vaccineBrowserManager0.updateVaccine(vaccine0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      VaccineType vaccineType0 = new VaccineType();
      Vaccine vaccine0 = new Vaccine("", "", vaccineType0);
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.newVaccine(vaccine0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.getVaccine();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      VaccineType vaccineType0 = new VaccineType();
      Vaccine vaccine0 = new Vaccine("AF<D_QN=>%", "AF<D_QN=>%", vaccineType0);
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.updateVaccine(vaccine0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      Vaccine vaccine0 = new Vaccine();
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.deleteVaccine(vaccine0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.findVaccine(",r4A|u ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }
}
